# Generated by Django 3.1.3 on 2020-11-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='お菓子A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('商品名', models.CharField(max_length=200)),
                ('dis_date', models.DateTimeField(verbose_name='賞味期限')),
            ],
        ),
        migrations.CreateModel(
            name='お菓子B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('商品名', models.CharField(max_length=200)),
                ('dis_date', models.DateTimeField(verbose_name='賞味期限')),
            ],
        ),
        migrations.CreateModel(
            name='お菓子C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('商品名', models.CharField(max_length=200)),
                ('dis_date', models.DateTimeField(verbose_name='賞味期限')),
            ],
        ),
        migrations.CreateModel(
            name='半生お菓子',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('商品名', models.CharField(max_length=200)),
                ('dis_date', models.DateTimeField(verbose_name='賞味期限')),
            ],
        ),
    ]
