# Generated by Django 3.1.3 on 2020-11-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockcheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='お菓子a',
            name='is_discounted',
            field=models.BooleanField(default=False, verbose_name='済み'),
        ),
        migrations.AddField(
            model_name='お菓子b',
            name='is_discounted',
            field=models.BooleanField(default=False, verbose_name='済み'),
        ),
        migrations.AddField(
            model_name='お菓子c',
            name='is_discounted',
            field=models.BooleanField(default=False, verbose_name='済み'),
        ),
        migrations.AddField(
            model_name='半生お菓子',
            name='is_discounted',
            field=models.BooleanField(default=False, verbose_name='済み'),
        ),
    ]
