# Generated by Django 3.1.3 on 2020-11-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockcheck', '0002_auto_20201116_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='お菓子a',
            options={'verbose_name': 'お菓子A', 'verbose_name_plural': 'お菓子A'},
        ),
        migrations.AlterModelOptions(
            name='お菓子b',
            options={'verbose_name': 'お菓子B', 'verbose_name_plural': 'お菓子B'},
        ),
        migrations.AlterModelOptions(
            name='お菓子c',
            options={'verbose_name': 'お菓子C', 'verbose_name_plural': 'お菓子C'},
        ),
        migrations.AlterModelOptions(
            name='半生お菓子',
            options={'verbose_name': '半生お菓子', 'verbose_name_plural': '半生お菓子'},
        ),
        migrations.AlterField(
            model_name='お菓子c',
            name='dis_date',
            field=models.DateTimeField(verbose_name='賞味'),
        ),
    ]
