# Generated by Django 3.1.3 on 2020-11-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockcheck', '0003_auto_20201116_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='カテゴリー')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリー',
            },
        ),
        migrations.RemoveField(
            model_name='お菓子a',
            name='is_discounted',
        ),
        migrations.RemoveField(
            model_name='お菓子b',
            name='is_discounted',
        ),
        migrations.RemoveField(
            model_name='お菓子c',
            name='is_discounted',
        ),
        migrations.RemoveField(
            model_name='半生お菓子',
            name='is_discounted',
        ),
        migrations.AlterField(
            model_name='お菓子a',
            name='dis_date',
            field=models.DateTimeField(verbose_name='賞味'),
        ),
        migrations.AlterField(
            model_name='お菓子b',
            name='dis_date',
            field=models.DateTimeField(verbose_name='賞味'),
        ),
        migrations.AlterField(
            model_name='半生お菓子',
            name='dis_date',
            field=models.DateTimeField(verbose_name='賞味'),
        ),
    ]
