# Generated by Django 3.1.3 on 2020-11-16 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockcheck', '0004_auto_20201116_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='お菓子a',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stockcheck.category'),
        ),
        migrations.AddField(
            model_name='お菓子b',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stockcheck.category'),
        ),
        migrations.AddField(
            model_name='お菓子c',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stockcheck.category'),
        ),
        migrations.AddField(
            model_name='半生お菓子',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stockcheck.category'),
        ),
    ]
