# Generated by Django 3.1.3 on 2020-11-16 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockcheck', '0005_auto_20201116_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='カテゴリー')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリー',
            },
        ),
        migrations.AlterField(
            model_name='お菓子a',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stockcheck.categorys'),
        ),
        migrations.AlterField(
            model_name='お菓子b',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stockcheck.categorys'),
        ),
        migrations.AlterField(
            model_name='お菓子c',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stockcheck.categorys'),
        ),
        migrations.AlterField(
            model_name='半生お菓子',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stockcheck.categorys'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
